platform :ios do
  desc "Build the Tabris.js Hello World App"
  lane :buildDebug do
    match(keychain_name: "jenkins-build.keychain", type: "development", git_url: "git@github.com:eclipsesource/match-certificates.git")
    # tabris build...
    sh "cd .. && tabris build ios --device --debug"
  end
  desc "Deploy App to the Appstore"
  lane :deploy do
    #appstore(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
  end
end
