name: Build master iOS app

on:
  push:
  schedule:
    - cron:  '15 5 * * *'
  repository_dispatch:
    types:
      - build-master-ios

jobs:
  build-ios:
    runs-on: macos-15
    name: Build Tabris.js Hello World iOS
    environment: 'iOS app build'
    strategy:
      matrix:
        build_type: [release, debug]
    steps:

      - name: Install the Apple certificate and provisioning profile
        uses: eclipsesource/prepare-for-signing-action@v1
        with:
          app_identifier: "${{ matrix.build_type == 'release' && 'com.eclipsesource.hello.world' || 'com.eclipsesource.*' }}"
          profile_type: "${{ matrix.build_type == 'release' && 'appstore' || 'development' }}"
          match_git_url: ${{ secrets.TABRIS_IOS_MATCH_GIT_URL }}
          match_git_branch: ${{ secrets.TABRIS_IOS_MATCH_GIT_BRANCH }}
          match_git_ssh_key: ${{ secrets.TABRIS_IOS_MATCH_GIT_SSH_KEY }}
          match_password: ${{ secrets.TABRIS_IOS_MATCH_PASSWORD }}
          fastlane_team_id: ${{ secrets.TABRIS_IOS_FASTLANE_TEAM_ID }}
          fastlane_user: ${{ secrets.TABRIS_IOS_FASTLANE_USER }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          path: tabris-js-hello-world
          fetch-depth: 1

      - name: Install tabris-cli
        run: npm install -g tabris-cli

      - name: Build tabris-js-hello-world
        env:
          TABRIS_BUILD_KEY: ${{ secrets.TABRIS_IOS_BUILD_KEY }}
        run: |
          cd tabris-js-hello-world
          npm install

          export BUILD_NUMBER="$(date +%y%m%d%H%M)"
          echo BUILD_NUMBER $BUILD_NUMBER

          tabris build ios --${{ matrix.build_type }} --device --verbose

      - name: AppStore Upload
        if: ${{ matrix.build_type == 'release' }}
        env:
          FASTLANE_USER: ${{ secrets.TABRIS_IOS_FASTLANE_USER }}
          FASTLANE_APP_SPECIFIC_PASSWORD: ${{ secrets.TABRIS_IOS_FASTLANE_APP_SPECIFIC_PASSWORD }}
        run: |
          xcrun altool --upload-app --type ios \
            --file "$(find . -iname "*.ipa")" \
            --username $FASTLANE_USER \
            --password '@env:FASTLANE_APP_SPECIFIC_PASSWORD'

      - name: Cleanup
        if: always()
        run: rm -Rf *
