name: Build 3.x iOS app

on:
  push:
  schedule:
    - cron:  '15 5 * * *'
  repository_dispatch:
    types:
      - build-3.x-nightly-ios

jobs:
  build-ios:
    runs-on: macos-latest
    name: Build Tabris.js Hello World iOS
    environment: 'iOS app build'
    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 3.x-nightly-nodejs18
          path: tabris-js-hello-world
          fetch-depth: 1

      - name: Checkout match-certificates
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.TABRIS_IOS_MATCH_GIT_URL }}
          ref: ${{ secrets.TABRIS_IOS_MATCH_GIT_BRANCH }}
          ssh-key: ${{ secrets.TABRIS_IOS_MATCH_GIT_SSH_KEY }}
          path: match
          fetch-depth: 1

      - name: Prepare keychain
        env:
          DEBUG_APP_IDENTIFIER: 'com.eclipsesource.*'
          RELEASE_APP_IDENTIFIER: 'com.eclipsesource.hello.world'
          FASTLANE_TEAM_ID: ${{ secrets.TABRIS_IOS_FASTLANE_TEAM_ID }}
          FASTLANE_USER: ${{ secrets.TABRIS_IOS_FASTLANE_USER }}
          MATCH_PASSWORD: ${{ secrets.TABRIS_IOS_MATCH_PASSWORD }}
          MATCH_GIT_URL: ./match
          MATCH_GIT_BRANCH: ${{ secrets.TABRIS_IOS_MATCH_GIT_BRANCH }}
          MATCH_KEYCHAIN_NAME: 'build.keychain'
          MATCH_KEYCHAIN_PASSWORD: 'foobar'
        run: |
          security create-keychain -p $MATCH_KEYCHAIN_PASSWORD $MATCH_KEYCHAIN_NAME
          security unlock-keychain -p $MATCH_KEYCHAIN_PASSWORD $MATCH_KEYCHAIN_NAME
          security set-keychain-settings -u -t 3600 $MATCH_KEYCHAIN_NAME
          security list-keychains -d user -s $MATCH_KEYCHAIN_NAME

          if [[ "${{ matrix.build_type }}" == "release" ]]; then
            fastlane match appstore --readonly --app_identifier ${{ env.RELEASE_APP_IDENTIFIER }}
          else
            fastlane match development --readonly --app_identifier ${{ env.DEBUG_APP_IDENTIFIER }}
          fi

      - name: Install tabris-cli
        run: npm install -g tabris-cli

      - name: Build tabris-js-hello-world
        env:
          TABRIS_BUILD_KEY: ${{ secrets.TABRIS_IOS_BUILD_KEY }}
        run: |
          cd tabris-js-hello-world
          npm install
          export BUILD_NUMBER="$(date +%y%m%d%H%M).3"
          echo BUILD_NUMBER $BUILD_NUMBER

          tabris build ios --${{ matrix.build_type }} --device --verbose

      - name: AppStore Upload
        if: ${{ matrix.build_type == 'release' }}
        env:
          DEVELOPER_DIR: /Applications/Xcode_12.5.1.app/Contents/Developer
          FASTLANE_USER: ${{ secrets.TABRIS_IOS_FASTLANE_USER }}
          FASTLANE_APP_SPECIFIC_PASSWORD: ${{ secrets.TABRIS_IOS_FASTLANE_APP_SPECIFIC_PASSWORD }}
        run: |
          xcrun altool --upload-app --type ios \
            --file "$(find . -iname "*.ipa")" \
            --username $FASTLANE_USER \
            --password '@env:FASTLANE_APP_SPECIFIC_PASSWORD'

      - name: Cleanup
        if: always()
        run: rm -Rf *
