name: App build
on: push

jobs:
  build_with_signing:
    runs-on: macos-latest
    environment: 'iOS app build'

    steps:
      - name: Install the Apple certificate and provisioning profile
        uses: eclipsesource/prepare-for-signing-action@main
        with:
          app_identifier: 'com.eclipsesource.*'
          profile_type: 'development'
          match_git_url: ${{ secrets.TABRIS_IOS_MATCH_GIT_URL }}
          match_git_branch: ${{ secrets.TABRIS_IOS_MATCH_GIT_BRANCH }}
          match_git_ssh_key: ${{ secrets.TABRIS_IOS_MATCH_GIT_SSH_KEY }}
          match_password: ${{ secrets.TABRIS_IOS_MATCH_PASSWORD }}
          fastlane_team_id: ${{ secrets.TABRIS_IOS_FASTLANE_TEAM_ID }}
          fastlane_user: ${{ secrets.TABRIS_IOS_FASTLANE_USER }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 3.x-nightly
          path: tabris-js-hello-world
          fetch-depth: 1

      - name: Build app
        env:
          TABRIS_BUILD_KEY: ${{ secrets.TABRIS_IOS_BUILD_KEY }}
        run: |
          cd tabris-js-hello-world
          npm install
          npm install --global tabris-cli 

          tabris --version
          pwd
          tabris build ios --device --debug --verbose

      - name: Prepare artifacts
        run: |
          ls -l "$(find . -iname "*.ipa")"
          ls -l "$(find . -iname "*.dSYM")"

          printenv | grep GITHUB > .env-gha

          tar cf artifacts.tar \
            "$(find . -iname "*.ipa")" \
            "$(find . -iname "*.dSYM")" \
            .env-gha

      - name: Archive metadata
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: artifacts.tar
          path: artifacts.tar
          retention-days: 1
